#!/bin/bash
#
# Setup script para o Probe (Satellite Controller)
# Instala dependências, configura ambiente e prepara para execução
#

set -e

echo "=============================================="
echo "  Greenbone Probe - Setup"
echo "=============================================="
echo ""

# Detectar diretório do script
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SATELLITE_DIR="$SCRIPT_DIR/satellite"

# Verificar se está no diretório correto
if [ ! -f "$SATELLITE_DIR/requirements.txt" ]; then
    echo "❌ Erro: Execute este script do diretório 'probe'"
    exit 1
fi

# ============================================
# 1. Instalar dependências do sistema
# ============================================
echo "📦 Instalando dependências do sistema..."

if command -v apt &> /dev/null; then
    apt update -qq
    apt install -y python3 python3-venv python3-pip curl docker.io docker-compose -qq
elif command -v yum &> /dev/null; then
    yum install -y python3 python3-pip curl docker docker-compose -q
else
    echo "⚠️  Sistema não suportado. Instale manualmente: python3, python3-venv, docker, docker-compose"
fi

# ============================================
# 2. Configurar ambiente Python
# ============================================
echo ""
echo "🐍 Configurando ambiente Python..."

cd "$SATELLITE_DIR"

# Criar venv se não existir
if [ ! -d "venv" ]; then
    python3 -m venv venv
    echo "   ✓ Virtual environment criado"
fi

# Ativar e instalar deps
source venv/bin/activate
pip install --upgrade pip -q
pip install -r requirements.txt -q
echo "   ✓ Dependências Python instaladas"

# ============================================
# 3. Coletar configurações
# ============================================
echo ""
echo "⚙️  Configuração do Probe"
echo "-------------------------------------------"

# Valores default
DEFAULT_PROBE_ID="probe-$(hostname | tr '[:upper:]' '[:lower:]')"
DEFAULT_PROBE_LOCATION="$(hostname)"
DEFAULT_GVM_HOST="localhost"
DEFAULT_GVM_PORT="9390"
DEFAULT_GVM_USER="admin"
DEFAULT_GVM_PASS="admin"
DEFAULT_NATS_URL=""
DEFAULT_WEBHOOK_URL=""

# Perguntar configs
read -p "Probe ID [$DEFAULT_PROBE_ID]: " PROBE_ID
PROBE_ID=${PROBE_ID:-$DEFAULT_PROBE_ID}

read -p "Probe Location [$DEFAULT_PROBE_LOCATION]: " PROBE_LOCATION
PROBE_LOCATION=${PROBE_LOCATION:-$DEFAULT_PROBE_LOCATION}

read -p "GVM Host [$DEFAULT_GVM_HOST]: " GVM_HOST
GVM_HOST=${GVM_HOST:-$DEFAULT_GVM_HOST}

read -p "GVM Port [$DEFAULT_GVM_PORT]: " GVM_PORT
GVM_PORT=${GVM_PORT:-$DEFAULT_GVM_PORT}

read -p "GVM Username [$DEFAULT_GVM_USER]: " GVM_USERNAME
GVM_USERNAME=${GVM_USERNAME:-$DEFAULT_GVM_USER}

read -s -p "GVM Password [$DEFAULT_GVM_PASS]: " GVM_PASSWORD
GVM_PASSWORD=${GVM_PASSWORD:-$DEFAULT_GVM_PASS}
echo ""

read -p "NATS URL (ex: nats://central:4222): " NATS_URL
read -p "NATS Token (deixe vazio se não usar): " NATS_TOKEN

read -p "Central Webhook URL (ex: https://central:8081/results): " CENTRAL_WEBHOOK
read -p "Probe Token (para autenticar no webhook): " PROBE_TOKEN

# ============================================
# 4. Criar arquivo .env
# ============================================
echo ""
echo "📝 Criando arquivo .env..."

cd "$SCRIPT_DIR"

cat > .env << EOF
# ===========================================
# Probe Configuration
# Generated by setup.sh on $(date)
# ===========================================

# Probe Identification
PROBE_ID=$PROBE_ID
PROBE_LOCATION=$PROBE_LOCATION
PROBE_TOKEN=$PROBE_TOKEN

# GVM/OpenVAS credentials
GVM_HOST=$GVM_HOST
GVM_PORT=$GVM_PORT
GVM_USERNAME=$GVM_USERNAME
GVM_PASSWORD=$GVM_PASSWORD

# Central Connection
NATS_URL=$NATS_URL
NATS_TOKEN=$NATS_TOKEN
CENTRAL_WEBHOOK=$CENTRAL_WEBHOOK

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=console

# OpenVAS Settings
AUTO_SYNC=true
HTTPS=true
EOF

echo "   ✓ Arquivo .env criado"

# ============================================
# 5. Mostrar próximos passos
# ============================================
echo ""
echo "=============================================="
echo "  ✅ Setup concluído!"
echo "=============================================="
echo ""
echo "Próximos passos:"
echo ""
echo "1. Subir OpenVAS (primeira vez demora ~5min):"
echo "   docker-compose up openvas -d"
echo "   docker logs -f greenbone-openvas"
echo ""
echo "2. Testar conexão com GVM:"
echo "   cd satellite"
echo "   source venv/bin/activate"
echo "   python -m src.test_gvm"
echo ""
echo "3. Rodar o Satellite Controller:"
echo "   source venv/bin/activate"
echo "   python -m src.main"
echo ""
echo "Ou use os scripts auxiliares:"
echo "   ./start.sh      # Inicia tudo"
echo "   ./stop.sh       # Para tudo"
echo "   ./test.sh       # Testa conexões"
echo ""
